Repository Hex-Clan-OOSD/donate-me, pull requests merged in 2022-01, with the labels that each got.

#68 Decorator design pattern added to navbars
  app/controllers/Pages.php
  app/views/inc/admin_navbar.php
  app/views/inc/navbar.php
  app/views/inc/normal_user_navbar.php
  app/views/pages/index.php
Labels: enhancement

#69 Navbars added for the admin and normal users
  app/controllers/Requests.php
  app/controllers/Users.php
Labels: enhancement

#70 More details removed and added to register
  app/controllers/Users.php
  app/models/User.php
  app/views/requests/index.php
  app/views/users/admin.php
  app/views/users/moredetails.php
Labels: enhancement

#73 Code formatter for CSS and Image not loading issue
  app/lib/Database.php
  app/views/inc/admin_navbar.php
  app/views/inc/favicon.php
  app/views/inc/land_navbar.php
  app/views/inc/navbar.php
  app/views/inc/normal_user_navbar.php
  app/views/inc/request_navbar.php
  app/views/requests/index.php
  app/views/users/admin.php
  app/views/users/register.php
  app/views/users/signin.php
Labels: bug

#72 Registe page successfully designed
  app/views/users/register.php
Labels: enhancement

#74 Adapter design pattern implemented
  app/lib/Database.php
  app/lib/DatabaseAdapter.php
  app/models/Notification.php
  app/models/Request.php
  app/models/User.php
Labels: enhancement

#77 User verifications backend
  ReadME.md
  app/controllers/Users.php
  app/models/User.php
  app/views/users/verifications.php
Labels: enhancement

#79 Request verifications backend
  .DS_Store
  app/controllers/Requests.php
  app/models/Request.php
  app/views/requests/pending.php
Labels: enhancement

#80 User confirmation connected with the backend.
  app/controllers/Users.php
  app/models/User.php
  app/views/users/verifications.php
Labels: enhancement

#81 File uploading added
  app/views/requests/add.php
  public/css/request_add_form_styles.css
Labels: enhancement

#83 Photo uploading added successfully
  .DS_Store
  ReadME.md
  app/controllers/Requests.php
  app/models/Request.php
  app/views/requests/add.php
  public/.DS_Store
  public/css/request_add_form_styles.css
  public/upload-images/photo-1552519507-da3b142c6e3d.jpeg
Labels: enhancement

#84 Landing page added and login conditions changed
  app/controllers/Pages.php
  app/views/donations/pending.php
  app/views/inc/admin_navbar.php
  app/views/inc/request_navbar.php
  app/views/pages/index.php
Labels: enhancement

#86 Images submitting added for the donations
  ReadME.md
  app/controllers/Donations.php
  app/models/Donation.php
  app/models/Request.php
  app/views/donations/adddonation.php
  public/.DS_Store
  public/upload-images/decoders.JPG
Labels: enhancement

#88 Admin user landing page issue fixed
  app/controllers/Users.php
Labels: enhancement

#89 Few modifications done
  app/config/config.php
  app/controllers/Donations.php
  app/controllers/Pages.php
  app/controllers/Requests.php
  app/models/Request.php
  app/views/pages/index.php
Labels: enhancement

#90 donation confirmation added successfully
  app/controllers/Donations.php
  app/models/Donation.php
  app/models/Request.php
  app/views/donations/pending.php
  public/.DS_Store
  public/upload-images/donation_image.jpeg
  public/upload-images/marvin-meyer-SYTO3xs06fU-unsplash.jpg
Labels: enhancement

#91 View collected amount issue fixed
  app/controllers/Pages.php
  app/models/Request.php
  app/views/pages/index.php
Labels: enhancement

#92 Singleton design pattern added for the database
  app/controllers/Notifications.php
  app/lib/Database.php
  app/lib/DatabaseAdapter.php
Labels: enhancement

#93 Page added for myrequests
  app/controllers/Requests.php
  app/views/inc/request_navbar.php
  app/views/requests/myrequests.php
Labels: enhancement

#94 Add notification function added succesfully
  ReadME.md
  app/controllers/Users.php
  app/models/Notification.php
  app/views/inc/admin_navbar.php
  app/views/users/addadmin.php
Labels: enhancement

#95 Notification adding
  ReadME.md
  app/controllers/Donations.php
  app/controllers/Requests.php
  app/models/Notification.php
  app/views/requests/pending.php
Labels: enhancement

#96 Donation rejected notification added
  app/controllers/Donations.php
Labels: enhancement

#97 Issue fixed
  app/controllers/Requests.php
  app/helpers/session_helper.php
  app/models/Request.php
  app/views/requests/index.php
Labels: bug

#98 my requests page added
  app/views/requests/myrequests.php
  public/css/home_styles.css
  public/images/myrequest.png
Labels: enhancement

#99 my requests connected to the backend succesfully
  app/controllers/Requests.php
  app/factories/RequestFactory.php
  app/models/Donation.php
  app/models/Request.php
  app/views/requests/myrequests.php
Labels: enhancement

#100 Navigation added
  app/controllers/Requests.php
Labels: enhancement

#102 Addadmin_page
  app/config/config.php
  app/controllers/Donations.php
  app/controllers/Notifications.php
  app/controllers/Pages.php
  app/controllers/Requests.php
  app/controllers/Users.php
  app/helpers/session_helper.php
  app/lib/Database.php
  app/lib/DatabaseAdapter.php
  app/models/Donation.php
  app/models/Notification.php
  app/models/Request.php
  app/views/donations/pending.php
  app/views/inc/admin_navbar.php
  app/views/inc/request_navbar.php
  app/views/pages/index.php
  app/views/requests/add.php
  app/views/requests/index.php
  app/views/requests/myrequests.php
  app/views/requests/pending.php
  app/views/users/addadmin.php
  app/views/users/admin.php
  public/.DS_Store
  public/css/addadmin_styles.css
  public/upload-images/donation_image.jpeg
  public/upload-images/marvin-meyer-SYTO3xs06fU-unsplash.jpg
Labels: enhancement

#101 notification page refine
  app/views/notifications/index.php
  public/css/home_styles.css
Labels: enhancement

#104 Addadmin page
  app/views/requests/add.php
  app/views/users/addadmin.php
  public/css/addadmin_styles.css
Labels: enhancement

#107 Add the admin adding page
  app/views/requests/add.php
  app/views/users/addadmin.php
  public/css/addadmin_styles.css
Labels: enhancement

#108 Refactoring done
  app/config/config.php
  app/controllers/Donations.php
  app/controllers/Requests.php
Labels: enhancement

#109 Issues fixed in the landing page
  app/controllers/Pages.php
  app/models/Request.php
  app/views/pages/index.php
Labels: bug, enhancement

#110 setting page created
  app/views/pages/settings.php
  public/css/setting_styles.css
Labels: enhancement

#111 Factory for user added
  app/factories/UserFactory.php
  app/models/User.php
  app/views/users/verifications.php
Labels: enhancement

#112 notification page refine
  app/views/notifications/index.php
  public/css/home_styles.css
Labels: enhancement

#113 design admin landing page
  app/views/pages/admin_landing.php
  public/css/landing_styles.css
  public/images/admin-landing.jpg
Labels: enhancement

#114 Notification showing
  app/controllers/Notifications.php
  app/controllers/Pages.php
  app/controllers/Users.php
  app/factories/UserFactory.php
  app/models/Notification.php
  app/models/Request.php
  app/models/User.php
  app/views/notifications/index.php
  app/views/pages/admin_landing.php
  app/views/pages/settings.php
  app/views/users/verifications.php
Labels: enhancement

#115 Notification issue fixed
  app/controllers/Notifications.php
  app/controllers/Requests.php
  app/controllers/Users.php
  app/helpers/session_helper.php
  app/models/Notification.php
Labels: enhancement

#116 Settings connect
  app/controllers/Pages.php
  app/models/User.php
  app/views/pages/settings.php
Labels: enhancement

#118 Connected succesfully
  app/controllers/Pages.php
  app/controllers/Users.php
  app/models/User.php
  app/views/pages/admin_landing.php
  app/views/users/addadmin.php
Labels: enhancement

#119 Dev
  app/controllers/Pages.php
  app/controllers/Users.php
  app/models/User.php
  app/views/pages/admin_landing.php
  app/views/pages/settings.php
  app/views/users/addadmin.php
Labels: enhancement

#120 Code reformatting for design patterns
  ReadME.md
  app/config/config.php
  app/controllers/Requests.php
  app/factories/RequestFactory.php
  app/factories/UserFactory.php
  app/models/Request.php
  app/views/requests/add.php
  public/upload-images/.DS_Store
  public/upload-images/requests/marvin-meyer-SYTO3xs06fU-unsplash.jpg
Labels: bug, enhancement

#123 Design patterns implementation
  app/controllers/Donations.php
  app/controllers/Notifications.php
  app/controllers/Requests.php
  app/controllers/Users.php
  app/factories/UserFactory.php
Labels: enhancement

#125 Code fixing
  app/controllers/Donations.php
  app/controllers/Pages.php
  app/controllers/Requests.php
  app/factories/RequestFactory.php
  app/models/Donation.php
  app/models/User.php
  app/views/donations/adddonation.php
  app/views/donations/pending.php
  app/views/inc/admin_navbar.php
  app/views/requests/add.php
  app/views/requests/index.php
  app/views/requests/myrequests.php
  app/views/requests/pending.php
  app/views/users/verifications.php
  public/upload-images/donations/markus-winkler-wLBVAF-kMR0-unsplash.jpg
  public/upload-images/requests/nick-fewings-2ykkF3oQb_c-unsplash.jpg
Labels: bug, enhancement
